package zero

var messages = map[string]string{
	"required":     "%s is required",
	"len":          "%s must be length %s",
	"min":          "%s must have minimum size %s",
	"max":          "%s must have maximum size %s",
	"eq":           "%s must be equal to %s",
	"ne":           "%s must not be equal to %s",
	"lt":           "%s must be less than %s",
	"lte":          "%s must be less than or equal to %s",
	"gt":           "%s must be greater than %s",
	"gte":          "%s must be greater than or equal to %s",
	"eqfield":      "",
	"eqcsfield":    "",
	"necsfield":    "",
	"gtcsfield":    "",
	"gtecsfield":   "",
	"ltcsfield":    "",
	"ltecsfield":   "",
	"nefield":      "",
	"gtefield":     "",
	"gtfield":      "",
	"ltefield":     "",
	"ltfield":      "",
	"alpha":        "%s must be an alpha value",
	"alphanum":     "%s must be an alphanumeric value",
	"numeric":      "%s must be a numeric value",
	"number":       "%s must be a number",
	"hexadecimal":  "%s must be a hexadecimal value",
	"hexcolor":     "%s must be a hexadecimal color value",
	"rgb":          "%s must be an rgb color value",
	"rgba":         "%s must be an rgba color value",
	"hsl":          "%s must be a hsl color value",
	"hsla":         "%s must be a hsla color value",
	"email":        "%s must be a valid email",
	"url":          "%s must be a valid url",
	"uri":          "%s must be a valid uri",
	"base64":       "%s must be a base64 encoded value",
	"contains":     "%s must contain %s",
	"containsany":  "%s must contain any of %s",
	"containsrune": "%s must contain rune %s",
	"excludes":     "%s must not include %s",
	"excludesall":  "%s must not include any of %s",
	"excludesrune": "%s must not include rune %s",
	"isbn":         "%s must be a valid isbn value",
	"isbn10":       "%s must be a valid isbn10 value",
	"isbn13":       "%s must be a valid isbn13 value",
	"uuid":         "%s must be a valid uuid value",
	"uuid3":        "%s must be a valid uuid3 value",
	"uuid4":        "%s must be a valid uuid4 value",
	"uuid5":        "%s must be a valid uuid5 value",
	"ascii":        "%s must be a valid ascii character",
	"printascii":   "%s must be a valid printable ascii character",
	"multibyte":    "%s must be a valid multibyte value",
	"datauri":      "%s must be a datauri value",
	"latitude":     "%s must be a valid latitude value",
	"longitude":    "%s must be a valid longitude value",
	"ssn":          "%s must be a valid ssn value",
	"ipv4":         "%s must be a valid ipv4 address",
	"ipv6":         "%s must be a valid ipv6 address",
	"ip":           "%s must be a valid ip address",
	"cidrv4":       "%s must be a valid cidrv4 block",
	"cidrv6":       "%s must be a valid cidrv6 block",
	"cidr":         "%s must be a valid cidr block",
	"tcp4_addr":    "%s must be a resolvable tcp4 address",
	"tcp6_addr":    "%s must be a resolvable tcp6 address",
	"tcp_addr":     "%s must be a resolvable tcp address",
	"udp4_addr":    "%s must be a resolvable udp4 address",
	"udp6_addr":    "%s must be a resolvable udp6 address",
	"udp_addr":     "%s must be a resolvable udp address",
	"ip4_addr":     "%s must be a resolvable ip4 address",
	"ip6_addr":     "%s must be a resolvable ip6 address",
	"ip_addr":      "%s must be a resolvable ip address",
	"unix_addr":    "%s must be a resolvable unix address",
	"mac":          "%s must be a valid mac address",
}
